fix: can't install because of @segment/loosely-validate-event
W20170823-03:07:05.368(0)? (STDERR) Error: Cannot find module
'@segment/loosely-validate-event'
W20170823-03:07:05.368(0)? (STDERR)     at
Function.Module._resolveFilename (module.js:489:15)
W20170823-03:07:05.369(0)? (STDERR)     at Function.Module._load
(module.js:439:25)
W20170823-03:07:05.369(0)? (STDERR)     at Module.require
(module.js:517:17)
W20170823-03:07:05.370(0)? (STDERR)     at require
(internal/module.js:11:18)
W20170823-03:07:05.370(0)? (STDERR)     at Object.<anonymous>
(/home/ubuntu/focuster/packages/meteor-segment.io/.npm/package/node_modules/analytics-node/lib/index.js:10:16)
W20170823-03:07:05.371(0)? (STDERR)     at Module._compile
(module.js:573:30)
W20170823-03:07:05.371(0)? (STDERR)     at Object.Module._extensions..js
(module.js:584:10)
W20170823-03:07:05.372(0)? (STDERR)     at Module.load
(module.js:507:32)
W20170823-03:07:05.372(0)? (STDERR)     at tryModuleLoad
(module.js:470:12)
W20170823-03:07:05.373(0)? (STDERR)     at Function.Module._load
(module.js:462:3)